### PR TITLE
Fix attaching github issue to page

### LINKED ISSUE #12: bmo changes break attach form handling
The attach form is different now and rob-bugson doesn't work with it.

The new form looks like this:

screenshot_2018-09-13 create new attachment for bug 1346891

It doesn't have the mode toggle any more.

### PR DESCRIPTION
**Pull request by willkg**
BMO changed their attachment form so it no longer has that toggle. This
updates rob-bugson to work with the new page.

Fixes #12

### CODE REVIEW

File: github-pr-background.js [hunk 1]
```diff
@@ -53,19 +53,21 @@ async function createAttachTab(msg) {
...
+        // Add PR link
+        let att = document.getElementById("att-textarea");
         att.value = "${attValue}";
-        desc.value = "${descValue}";
+        // Trigger an input event so the textarea input handling kicks off.
+        var input_event = new Event('input', {
+            bubbles: true,
+            cancelable: true
+        });
+        att.dispatchEvent(input_event);
```
Comment (willkg) [inline github-pr-background.js:67]: Is this a good way to create and dispatch an event? Are there better ways? Does it have appropriate properties?

**Review by pmac — APPROVED** [review]
👍

File: github-pr-background.js [hunk 2]
```diff
@@ -53,19 +53,21 @@ async function createAttachTab(msg) {
...
-    // We need to add values for this specific attachment, so we
-    // build the template with local values and then execute the
-    // code in the tab.
+    // We need to add values for this specific attachment, so we build the
+    // template with local values and then execute the code in the tab.
     var attachScript = `
-        // switch from upload-file to paste-text attachment
-        if (document.querySelector(".attachment_text_field.bz_tui_hidden")) {
-            document.getElementById("attachment_data_controller").click();
-        }
```
Comment (willkg) [inline github-pr-background.js:63]: The attachment form no longer has this toggle, so we can nix this.
