### PR TITLE
Remove # from prURL value (#38)

### LINKED ISSUE #38: sometimes pr attachments get the wrong content-type
@calixteman had a case where he attached a pr using rob-bugson, but Bugzilla shows the PR wrong:

https://bugzilla.mozilla.org/show_bug.cgi?id=1726183#c4

Most of the time Bugzilla shows the PR correctly:

https://bugzilla.mozilla.org/show_bug.cgi?id=1687987#c5

As near as I can tell, rob-bugson is filling out the form the same way every time. It's unclear why it ever ends up wrong.

### PR DESCRIPTION
**Pull request by willkg**
Sometimes the url has a # at the end and when rob-bugson uses that to attach the pr to a Bugzilla bug, it causes Bugzilla to attach the pr as a text/plain and then everything goes sideways.

This fixes getPRUrl to remove # if it's there.

To test:

1. pick a PR that has a corresponding bug like this one: https://github.com/mozilla-services/socorro-submitter/pull/46
2. in the url bar, add a `#` and hard-refresh the page
3. click on the link to attach the PR

Before this fix, Bugzilla attaches the PR wrong. After this fix, Bugzilla attaches the PR correctly.

Fixes #38.

### CODE REVIEW

File: github-bugzilla-content.js [hunk 1]
```diff
@@ -58,7 +58,11 @@ function getPRTitle() {
  * Retrieve the PR url
  */
 function getPRUrl() {
-    return document.URL;
+    let url = document.URL;
+    if (url.indexOf("#") != -1) {
```
Comment (calixteman) [inline github-bugzilla-content.js]: You can likely simplify into: `return url.replace(/#$/, "");`

Comment (calixteman) [reply github-bugzilla-content.js]: My bad it's to remove only the final #.
Anyway to do the same: `return url.replace(/#.*/, "");` should be ok.

**Review by calixteman — APPROVED** [review]

**Comment by willkg** [comment]
Thank you!
